const { test } = require('node:test');
const assert = require('node:assert/strict');
const express = require('express');
const jwt = require('jsonwebtoken');
const bcrypt = require('bcryptjs');
const User = require('../models/User');
const { requireAuth } = require('../middleware/authMiddleware');
const routes = require('../routes/adminRoutes');

test('admin endpoints enforce authentication, database roles and safe creation', async (t) => {
  process.env.JWT_SECRET = 'admin-tests-only-secret-not-for-production';
  let currentRole = 'admin';
  let saved;
  let duplicate = false;
  t.mock.method(User, 'findById', () => ({ select: async () => ({ id: 'admin-id', role: currentRole, tokenVersion: 0, isEmailVerified: true }) }));
  t.mock.method(User, 'create', async (details) => {
    if (duplicate) throw Object.assign(new Error('duplicate'), { code: 11000 });
    saved = details;
    return { ...details, _id: 'new-id' };
  });
  t.mock.method(User, 'find', () => ({ select: () => ({ sort: async () => [{ _id: 'admin-id', name: 'Admin', email: 'admin@example.com', role: 'admin', password: 'hidden' }] }) }));
  const app = express();
  app.use(express.json());
  app.use('/api/admin', requireAuth, routes);
  const server = app.listen(0, '127.0.0.1');
  await new Promise((resolve) => server.once('listening', resolve));
  t.after(() => new Promise((resolve) => server.close(resolve)));
  const base = `http://127.0.0.1:${server.address().port}/api/admin`;
  const token = jwt.sign({ id: 'admin-id', role: 'admin', tokenVersion: 0 }, process.env.JWT_SECRET, { issuer: 'smartopd', expiresIn: '1h' });
  const headers = { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' };
  const body = { name: ' New Admin ', email: ' NEW@example.com ', password: 'Secure-Test123!', role: 'patient' };
  assert.equal((await fetch(`${base}/dashboard`)).status, 401);
  currentRole = 'patient';
  assert.equal((await fetch(`${base}/dashboard`, { headers })).status, 403);
  assert.equal((await fetch(`${base}/admins`, { method: 'POST', headers, body: JSON.stringify(body) })).status, 403);
  assert.equal(saved, undefined);
  currentRole = 'admin';
  const listing = await (await fetch(`${base}/dashboard`, { headers })).json();
  assert.equal(listing.admins[0].password, undefined);
  assert.equal((await fetch(`${base}/admins`, { method: 'POST', headers, body: JSON.stringify({ ...body, password: 'weak' }) })).status, 400);
  const response = await fetch(`${base}/admins`, { method: 'POST', headers, body: JSON.stringify(body) });
  assert.equal(response.status, 201);
  const data = await response.json();
  assert.equal(data.admin.password, undefined);
  assert.equal(data.token, undefined);
  assert.equal(saved.role, 'admin');
  assert.equal(saved.email, 'new@example.com');
  assert.equal(saved.isEmailVerified, true);
  assert.equal(await bcrypt.compare(body.password, saved.password), true);
  duplicate = true;
  assert.equal((await fetch(`${base}/admins`, { method: 'POST', headers, body: JSON.stringify(body) })).status, 409);
});
